[package]
name = "teleporter"
version = "0.9.2"
authors = ["geno nullfree <nullfree.geno@gmail.com>"]
license = "BSD-3-Clause"
description = "A small utility to send files quickly from point A to point B"
readme = "README.md"
homepage = "https://github.com/genonullfree/teleport.git"
repository = "https://github.com/genonullfree/teleport.git"
keywords = ["netcat", "teleport", "teleporter", "transfer", "send"]
categories = ["command-line-utilities", "network-programming"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.13"
byteorder = "1.4.3"
xxhash-rust = { version = "0.8.2", features = ["xxh3"] }
aes-gcm = "0.9.4"
generic-array = "0.14.4"
x25519-dalek = "1.2.0"
semver = "1.0.4"
rand = "0.8.4"
rand_core = { version = "0.5", default-features = false }
rndz = { version = "0.1.2", git="https://github.com/optman/rndz", default-features=false, features=["client"]}
env_logger="*"
